# Note: It requires docker-compose 1.13.0
#
# Usage: docker-compose up -d
version: "3.1"

services:
  # Selenium hub
  selenium_hub:
    image: selenium/hub:3.14.0-curium
    ports:
      - 4444:4444

  # There is a bug for using appium. Issue: https://github.com/budtmo/docker-android/issues/73
  # Real devices
  #real_device:
  #  image: budtmo/docker-android-real-device
  #  privileged: true
  #  depends_on:
  #    - selenium_hub
  #  ports:
  #    - 6080:6080
  #  volumes:
  #    - ./video-real-device:/tmp/video
  #    - /dev/bus/usb:/dev/bus/usb
  #    - ~/.android:/root/.android
  #  environment:
  #    - CONNECT_TO_GRID=true
  #    - APPIUM=true
  #    - SELENIUM_HOST=selenium_hub
  #    - AUTO_RECORD=true
  #    - BROWSER_NAME=chrome

  # Using Appium Docker Android  

  # Docker-Android for mobile website testing with chrome browser
  # Chrome browser exists only for version 7.0 and 7.1.1
  samsung_galaxy_web_7.1.1:
    image: budtmo/docker-android-x86-8.1
    privileged: true
    # Increase scale number if needed
    depends_on: 
      - selenium_hub
      - real_device
    ports:
      - 6080
    volumes:
      - ./video-samsung_7.1.1:/tmp/video
    environment:
      - DEVICE=Samsung Galaxy S6
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - MOBILE_WEB_TEST=true
      - AUTO_RECORD=true

